/*
 * @Author: DI JUNKUN
 * @Date: 2024-06-14
 * Copyright (c) 2024 by DI JUNKUN, All Rights Reserved.
 */

#ifndef _LAYOUT_STYLE_H_
#define _LAYOUT_STYLE_H_

#ifdef _WIN32
#define MENU_WINDOW_WIDTH_CN 160
#define MENU_WINDOW_HEIGHT_CN 245
#define MENU_WINDOW_WIDTH_EN 190
#define MENU_WINDOW_HEIGHT_EN 245
#define IPUT_WINDOW_WIDTH 86
#define INPUT_WINDOW_PADDING_CN 66
#define INPUT_WINDOW_PADDING_EN 96
#define SETTINGS_WINDOW_WIDTH_CN 181
#define SETTINGS_WINDOW_WIDTH_EN 228
#define SETTINGS_WINDOW_HEIGHT_CN 190
#define SETTINGS_WINDOW_HEIGHT_EN 190
#define LANGUAGE_SELECT_WINDOW_PADDING_CN 100
#define LANGUAGE_SELECT_WINDOW_PADDING_EN 147
#define VIDEO_QUALITY_SELECT_WINDOW_PADDING_CN 100
#define VIDEO_QUALITY_SELECT_WINDOW_PADDING_EN 147
#define VIDEO_ENCODE_FORMAT_SELECT_WINDOW_PADDING_CN 100
#define VIDEO_ENCODE_FORMAT_SELECT_WINDOW_PADDING_EN 147
#define ENABLE_HARDWARE_VIDEO_CODEC_CHECKBOX_PADDING_CN 154
#define ENABLE_HARDWARE_VIDEO_CODEC_CHECKBOX_PADDING_EN 201
#define SETTINGS_SELECT_WINDOW_WIDTH 73
#define SETTINGS_OK_BUTTON_PADDING_CN 55
#define SETTINGS_OK_BUTTON_PADDING_EN 78
#elif __linux__
#define MENU_WINDOW_WIDTH_CN 160
#define MENU_WINDOW_HEIGHT_CN 245
#define MENU_WINDOW_WIDTH_EN 190
#define MENU_WINDOW_HEIGHT_EN 245
#define IPUT_WINDOW_WIDTH 90
#define INPUT_WINDOW_PADDING_CN 60
#define INPUT_WINDOW_PADDING_EN 80
#define SETTINGS_WINDOW_WIDTH_CN 188
#define SETTINGS_WINDOW_WIDTH_EN 228
#define SETTINGS_WINDOW_HEIGHT_CN 190
#define SETTINGS_WINDOW_HEIGHT_EN 190
#define LANGUAGE_SELECT_WINDOW_PADDING_CN 100
#define LANGUAGE_SELECT_WINDOW_PADDING_EN 140
#define VIDEO_QUALITY_SELECT_WINDOW_PADDING_CN 100
#define VIDEO_QUALITY_SELECT_WINDOW_PADDING_EN 140
#define VIDEO_ENCODE_FORMAT_SELECT_WINDOW_PADDING_CN 100
#define VIDEO_ENCODE_FORMAT_SELECT_WINDOW_PADDING_EN 140
#define ENABLE_HARDWARE_VIDEO_CODEC_CHECKBOX_PADDING_CN 161
#define ENABLE_HARDWARE_VIDEO_CODEC_CHECKBOX_PADDING_EN 201
#define SETTINGS_SELECT_WINDOW_WIDTH 60
#define SETTINGS_OK_BUTTON_PADDING_CN 60
#define SETTINGS_OK_BUTTON_PADDING_EN 80
#elif __APPLE__
#define MENU_WINDOW_WIDTH_CN 148
#define MENU_WINDOW_HEIGHT_CN 244
#define MENU_WINDOW_WIDTH_EN 148
#define MENU_WINDOW_HEIGHT_EN 244
#define IPUT_WINDOW_WIDTH 77
#define INPUT_WINDOW_PADDING_CN 63
#define INPUT_WINDOW_PADDING_EN 63
#define SETTINGS_WINDOW_WIDTH_CN 160
#define SETTINGS_WINDOW_WIDTH_EN 220
#define SETTINGS_WINDOW_HEIGHT_CN 190
#define SETTINGS_WINDOW_HEIGHT_EN 190
#define LANGUAGE_SELECT_WINDOW_PADDING_CN 90
#define LANGUAGE_SELECT_WINDOW_PADDING_EN 150
#define VIDEO_QUALITY_SELECT_WINDOW_PADDING_CN 90
#define VIDEO_QUALITY_SELECT_WINDOW_PADDING_EN 150
#define VIDEO_ENCODE_FORMAT_SELECT_WINDOW_PADDING_CN 90
#define VIDEO_ENCODE_FORMAT_SELECT_WINDOW_PADDING_EN 150
#define ENABLE_HARDWARE_VIDEO_CODEC_CHECK_WINDOW_PADDING_CN 133
#define ENABLE_HARDWARE_VIDEO_CODEC_CHECK_WINDOW_PADDING_EN 193
#define SETTINGS_SELECT_WINDOW_WIDTH 62
#define SETTINGS_OK_BUTTON_PADDING_CN 50
#define SETTINGS_OK_BUTTON_PADDING_EN 80
#endif

#endif